/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:31b290d1-1a11-4993-b34e-51e6d2cfc672",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_f7S191UyJ",
    "aws_user_pools_web_client_id": "2espga3nsvc0b9t88igdhou7mq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://umtank4oxzh4tg2btjylvkqjoi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tbdprwjuabebbczrmhafo2xwta",
    "aws_user_files_s3_bucket": "thecodeschool-amplify22553-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
